[server]
port = 8000
address = "0.0.0.0"
maxUploadSize = 10

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#2E3A59"

[browser]
gatherUsageStats = false